<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>DanishVoice.Native.Cli</AssemblyName>
    <RootNamespace>DanishVoice.Native.Cli</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DanishVoice.Native\DanishVoice.Native.csproj" />
  </ItemGroup>

</Project>
